services:
  swagger-ui-besy:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: "$APP_NAME"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$APP_NAME.entrypoints=websecure"
      - "traefik.http.routers.$APP_NAME.rule=Host($APP_URL)"
      - "traefik.http.routers.$APP_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$APP_NAME.loadbalancer.server.port=$APP_PORT"
    networks:
      - traefik
    volumes:
      - ./swagger.yaml:/swagger.yaml:ro
    environment:
      - SWAGGER_JSON=/swagger.yaml
networks:
  traefik:
    external: true
